# properties ??
# server.port=8181

#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=

#yml ??
server:
  port: 8181

logging:
  level:
    root: info
    com:
      example:
        apibasic:
          req: trace

# 2023-01-16
#swagger
springdoc:
  swagger-ui:
    path: /myapi.html

spring:
  #database connection
  datasource:
    url: jdbc:mariadb://localhost:3306/demodb
    username: root
    password: mariadb
  #jpa config
  jpa:
    database: mysql   # 실제사용할 dbms 지정
    database-platform: org.hibernate.dialect.MariaDB106Dialect    # 방언 설정
    show-sql: true    # 실행되는 SQL 문 로그를 볼 것인지
    generate-ddl: true    # 각 DBMS 에 맞는 고유 기능을 사용할 지의 여부
    hibernate:
      ddl-auto: create    # DDL 문을 처리할 때 설정

# create : 매 실행마다 DDL 을 재실행
# update : 매 실행마다 바뀐 부분의 DDL 을 ALTER 문으로 수정
# none : DDL 을 실행하지 않음 - 운영서버에서는 none 으로 둔다.