# properties ??
# server.port=8181

#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=

#yml ??
server:
  port: 8181

#spring:
#  datasource:
#    url: xxx
#    username: xxx
#    password: xxx